import './globals.css';
import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <>{children}</>
        <footer>
          Copyright 2023. All rights reserved.
        </footer>
      </body>   
    </html>
  )
}
